import glob
import pandas as pd
import sys
import os
import csv
from src.utils.CSV_Files_To_DataFrame import CSV_to_DF

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
sys.path.insert(0, os.path.join(BASE_DIR, "../../pyIDS"))

from pyids.algorithms.ids_classifier import mine_CARs
from src.utils.Print_Helper import MyPrint

def save_cars_to_csv(cars, output_directory):
    if not cars:
        MyPrint("Mining_Cars_Func", "No CARs to save.", error=True, line_num=15)
        return
    
    # Convert CARs to dictionaries
    car_dicts = []
    for car in cars:
        car_dicts.append({
            "antecedent": str(car.antecedent),
            "consequent": str(car.consequent),
            "support": car.support,
            "confidence": car.confidence,
            "f1": getattr(car, "f1", None)  # some CARs may not have F1
        })
    
    # Write to CSV
    with open(output_directory, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=car_dicts[0].keys())
        writer.writeheader()
        writer.writerows(car_dicts)
    
    MyPrint("Mining_Cars_Func", f"Saved {len(cars)} CARs to {output_directory}")

def Mine_Cars(rule_cutoff, df, output_dir):
    df['class'] = df['class'].astype(str)
    MyPrint("Mining_Cars_Func", f"Total rows loaded: {len(df)}")

    cars = mine_CARs(df, rule_cutoff=rule_cutoff)
    MyPrint("Mining_Cars_Func", f"Mined CARs Count: {len(cars)}") # CARS are the rules generated by pyARC that pyIDS will select
    save_cars_to_csv(cars, output_dir)
    return cars