import glob
import pandas as pd
import sys
import os
import csv
from src.utils.CSV_Files_To_DataFrame import CSV_to_DF

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
sys.path.insert(0, os.path.join(BASE_DIR, "../../pyIDS"))

from pyids.algorithms.ids_classifier import mine_CARs
from src.utils.Print_Helper import MyPrint

def save_cars_to_csv(cars, output_directory):
    if not cars:
        MyPrint("Mining_Cars_Func", "No CARs to save.", error=True, line_num=15)
        return
    
    # Convert CARs to dictionaries
    car_dicts = []
    for car in cars:
        car_dicts.append({
            "antecedent": str(car.antecedent),
            "consequent": str(car.consequent),
            "support": car.support,
            "confidence": car.confidence,
            "f1": getattr(car, "f1", None)  # some CARs may not have F1
        })
    
    # Write to CSV
    with open(output_directory, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=car_dicts[0].keys())
        writer.writeheader()
        writer.writerows(car_dicts)
    
    MyPrint("Mining_Cars_Func", f"Saved {len(cars)} CARs to {output_directory}")

def Mine_Cars(max_rows, rule_cutoff, data_dir, output_dir):
    csv_files = glob.glob(os.path.join(data_dir, "*.csv"))
    MyPrint("Mining_Cars_Func", f"Number of CSV files found: {len(csv_files)}")

    df_list = []
    total_rows = 0
    for file in csv_files:
        temp_df = pd.read_csv(file)
        remaining_rows = max_rows - total_rows
        if remaining_rows <= 0:
            break
        if len(temp_df) > remaining_rows:
            temp_df = temp_df.head(remaining_rows)
        df_list.append(temp_df)
        total_rows += len(temp_df)

    if (total_rows == 0):
        MyPrint("Mining_Cars_Func", "Error, no rows found in data directory: " + data_dir, error=True, line_num=30)
        return

    df = CSV_to_DF(data_dir, max_rows=max_rows)
    df['class'] = df['class'].astype(str)
    MyPrint("Mining_Cars_Func", f"Total rows loaded: {len(df)}")

    cars = mine_CARs(df, rule_cutoff=rule_cutoff)
    MyPrint("Mining_Cars_Func", f"Mined CARs Count: {len(cars)}\n") # CARS are the rules generated by pyARC that pyIDS will select
    save_cars_to_csv(cars, output_dir)
    return cars